name: Build 16MB Pico Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build with Project Docker
        run: |
          docker build --output=./output .

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: pico-16mb-firmware
          path: ./output/*.uf2
