name: Build 16MB Pico Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM GCC Toolchain
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake ninja-build

      - name: Configure and Build (16MB Target)
        run: |
          mkdir build
          cd build
          cmake -DPICO_FLASH_SIZE_BYTES=16777216 ..
          make -j$(nproc)

      - name: Upload Built Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pico-16mb-firmware
          path: build/*.uf2
